export const FETCH_PRODUCTS_SHOP_REQUEST = "FETCH_PRODUCTS_SHOP_REQUEST";
export const FETCH_LOGOUT_PRODUCTS_SHOP_REQUEST = "FETCH_LOGOUT_PRODUCTS_SHOP_REQUEST";
export const FETCH_PRODUCTS_SHOP_SUCCESS = "FETCH_PRODUCTS_SHOP_SUCCESS";
export const FETCH_PRODUCTS_SHOP_FAIL = "FETCH_PRODUCTS_SHOP_FAIL";